#!/usr/bin/env bash

signature=$(find $BUILDKITE_PLUGIN_DOCKER_BUILD_KEYS -type f  | sort | xargs md5sum | md5sum | cut -d ' ' -f 1)
image_with_tag=${BUILDKITE_PLUGIN_DOCKER_BUILD_IMAGE_PREFIX}{signature}
echo "Preparing image: ${image_with_tag}"

local_image=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep $image_with_tag)

if [[ $local_image ]]; then
  echo "Using local image: ${local_image}"
else
  echo "Pulling remote image..."
  docker pull $image_with_tag

  if [[ $? -eq 0 ]]; then
    echo "Pulled remote image successfully"
  else
    echo "Image does not exist remotely, building the image..."
    set -e
    docker build -f ${BUILDKITE_PLUGIN_DOCKER_BUILD_DOCKER_FILE} -t $image_with_tag .
    echo "Pushing image..."
    docker push $image_with_tag
    buildkite-agent metadata set $BUILDKITE_PLUGIN_DOCKER_BUILD_METADATA $image_with_tag
  fi
fi
